In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Parameters
pop_size = 500
string_length = 30
mutation_rate = 0.00001
#crossover_rate = 0.7
generations = 200


In [2]:
# Function to initialize the population
def initialize_population():
    return np.random.randint(2, size=(pop_size, string_length))

# Function to calculate fitness
def calculate_fitness(population):
    return np.sum(population, axis=1)

# Function for mutation
def mutate(child):
    mutation_mask = np.random.rand(string_length) < mutation_rate
    child[mutation_mask] = 1 - child[mutation_mask]  # Flip 0s to 1s and vice versa
    return child

# Function for crossover
def crossover(parent1, parent2):
    crossover_point = np.random.randint(1, string_length)
    child1 = np.concatenate((parent1[:crossover_point], parent2[crossover_point:]))
    child2 = np.concatenate((parent2[:crossover_point], parent1[crossover_point:]))
    return child1, child2

In [5]:
# Main genetic algorithm loop
population = initialize_population()
fitness_history = []

while True:
    fitness_values = calculate_fitness(population)
    average_fitness = np.mean(fitness_values)
    fitness_history.append(average_fitness)
    
    if average_fitness >= 30:
        break

    # Select parents based on fitness
    parents = population[np.random.choice(pop_size, size=pop_size // 2, p=fitness_values / np.sum(fitness_values))]

    # Create next generation through crossover and mutation
    children = []
    for i in range(0, pop_size // 2, 2):
        child1, child2 = crossover(parents[i], parents[i + 1])
        child1 = mutate(child1)
        child2 = mutate(child2)
        children.extend([child1, child2])

    population[:pop_size // 2] = parents
    population[pop_size // 2:] = children


In [65]:
# Set the desired number of decimal places (e.g., 2 in this case)
decimal_places = 5

# Create a format string with the desired precision
format_string = f'%.{decimal_places}f'

# Convert to strings with the specified precision
fitness_history = [format_string % num for num in fitness_history]

# Save to a text file
np.savetxt('fitness_history.txt', fitness_history, fmt='%s')

In [66]:
#plt.plot(range(1,51), fitness_history)

In [67]:
#for x in population:
#    print(x)
# 500 163 0.00001
# 200 

In [69]:
for x in range(0,190):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189


In [4]:
population = initialize_population()
print(population)

[[0 0 1 ... 0 1 1]
 [1 0 1 ... 0 1 0]
 [1 0 0 ... 1 1 0]
 ...
 [1 0 0 ... 1 1 0]
 [1 1 0 ... 0 0 1]
 [0 0 0 ... 0 1 1]]


In [6]:
print(fitness_values)

[30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30
 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30